services:
  frontend:
    container_name: frontend
    build:
      context: .
      args:
        MONGODB_URI: ${MONGODB_URI}
        DB_NAME: ${DB_NAME}
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
