services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NEXT_WEBPACK_USEPOLLING=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 80:3000
