name: cloud-run.deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: asia-southeast1
  REPO_NAME: tikku

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |-
          echo "REGISTRY=$REGION-docker.pkg.dev" >> $GITHUB_ENV

      - run: |-
          echo "IMAGE_NAME=$REGISTRY/$PROJECT_ID/$REPO_NAME/main:$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Authenticate with Google Cloud
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker $REGISTRY

      - name: Build and tag the docker image
        env:
          MONGODB_URI: "${{ secrets.MONGODB_URI }}"
        run: |-
          docker build . --tag $IMAGE_NAME

      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push $IMAGE_NAME

      - name: Deploy
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image $IMAGE_NAME \
          --platform "managed" \
          --quiet
